name: Deploy WordPress
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 mysql-server php-mysql

      - name: Configure Apache
        run: |
          sudo sed -i 's/\/var\/www\/html/\/var\/www\/wordpress/g' /etc/apache2/sites-available/000-default.conf
          sudo systemctl restart apache2

      - name: Set up MySQL
        run: |
          
          sudo mysql -e "CREATE DATABASE wordpress;"
          sudo mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'password';"
          sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost';"
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Download and Configure WordPress
        run: |
          sudo wget https://wordpress.org/latest.tar.gz
          sudo tar -xf latest.tar.gz
          sudo cp -R wordpress/* /var/www/wordpress/
          sudo chown -R www-data:www-data /var/www/wordpress/
          sudo chmod -R 755 /var/www/wordpress/

      - name: Set up Environment Variables
        run: |
          echo "DB_NAME=wordpress" >> $GITHUB_ENV
          echo "DB_USER=wordpress" >> $GITHUB_ENV
          echo "DB_PASSWORD=password" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV

      - name: Configure WordPress
        run: |
          cd /var/www/wordpress/
          mv wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/$DB_NAME/g" wp-config.php
          sed -i "s/username_here/$DB_USER/g" wp-config.php
          sed -i "s/password_here/$DB_PASSWORD/g" wp-config.php
          sed -i "s/localhost/$DB_HOST/g" wp-config.php
