name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: |
            mysqli
            gd
            zip
            opcache
      
      - name: Install Composer dependencies
        run: composer install
      
      - name: Set up MySQL
        uses: azure/setup-mysql@v1
        with:
          mysql-version: '5.7'
          mysql-server-name: ${{ secrets.MYSQL_SERVER_NAME }}
          mysql-server-user: ${{ secrets.MYSQL_SERVER_USER }}
          mysql-server-password: ${{ secrets.MYSQL_SERVER_PASSWORD }}
      
      - name: Create database
        run: mysql -h ${{ secrets.MYSQL_SERVER_NAME }} -u ${{ secrets.MYSQL_SERVER_USER }} -p${{ secrets.MYSQL_SERVER_PASSWORD }} -e "CREATE DATABASE wordpress;"
      
      - name: Configure WordPress
        run: |
          cp .env.example .env
          sed -i "s/DB_NAME=.*/DB_NAME=wordpress/" .env
          sed -i "s/DB_USER=.*/DB_USER=${{ secrets.MYSQL_SERVER_USER }}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${{ secrets.MYSQL_SERVER_PASSWORD }}/" .env
      
      - name: Start web server
        run: php -S localhost:8000 -t public/
        background: true
      
      - name: Wait for web server to start
        run: sleep 3
      
      - name: Run WordPress tests
        run: vendor/bin/phpunit
      
      - name: Deploy to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ./
          target: /var/www/html/
          args: -r
