name: Deploy WordPress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and configure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2 php mysql-client
          sudo apt-get install -y php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ./key.pem
          script: |
            # Commands to deploy WordPress
            cd /var/www/html
            sudo wget https://wordpress.org/latest.tar.gz
            sudo tar -xzvf latest.tar.gz
            sudo chown -R www-data:www-data wordpress/
            sudo chmod -R 755 wordpress/

            # Configure WordPress
            cd wordpress
            sudo mv wp-config-sample.php wp-config.php
            sudo sed -i "s/database_name_here/${{ secrets.DB_NAME }}/g" wp-config.php
            sudo sed -i "s/username_here/${{ secrets.DB_USERNAME }}/g" wp-config.php
            sudo sed -i "s/password_here/${{ secrets.DB_PASSWORD }}/g" wp-config.php

            # Restart Apache
            sudo service apache2 restart
